# Generated by Django 3.1.7 on 2021-07-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci_dashboardApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='token',
            name='oneToken_OneUser_OneCI',
        ),
        migrations.AddField(
            model_name='token',
            name='access',
            field=models.CharField(default=None, max_length=7, null=True),
        ),
        migrations.AddConstraint(
            model_name='token',
            constraint=models.UniqueConstraint(fields=('ci', 'user', 'access'), name='oneToken_OneUser_OneCI_OneAccess'),
        ),
    ]
