# Generated by Django 3.1.7 on 2021-09-08 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ci_dashboardApp', '0003_auto_20210902_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ci',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ci', to='ci_dashboardApp.group'),
        ),
    ]
