# Generated by Django 4.2.6 on 2023-10-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci_dashboardApp', '0004_auto_20210908_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='branch',
            field=models.CharField(default='main', max_length=60),
        ),
        migrations.AddField(
            model_name='job',
            name='workflow',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
