# Generated by Django 4.2.6 on 2023-10-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci_dashboardApp', '0005_job_branch_job_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='branch',
            field=models.CharField(default='main', max_length=60, null=True),
        ),
    ]
